[package]
name = "gnag"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.13.0"

[dependencies.profiling]
version = "1.0.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
