[package]
name = "gnag-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
gnag-parser = { path = "../gnag-parser" }
gnag-backend = { path = "../gnag-backend" }
code-render = { path = "../code-render" }
linemap = { path = "../linemap" }
